### ISSUE TITLE
No modules load

### ISSUE THREAD

**Issue by MiyuriWise** [regzo2/VRCFaceTracking-MeowFace#14]
Idk whats wrong i put everywhere right ip and number but its says the same

![image](https://github.com/user-attachments/assets/9d3ccd42-617f-48fe-a784-c0d471a91455)
![image](https://github.com/user-attachments/assets/62a66517-76ca-42de-9acd-eadec64db2cc)

[VRCFaceTracking.Services.ActivationService] Information: VRCFT Version 5.2.3.0 initializing...
[VRCFaceTracking.Services.ActivationService] Information: Initializing OSC...
[VRCFaceTracking.Core.OSC.OscQueryService] Debug: OSC Service Initializing
[VRCFaceTracking.Core.OSC.OscQueryService] Debug: OSC Service Initialized with result (False, False)
[VRCFaceTracking.Services.ActivationService] Information: Initializing main service...
[VRCFaceTracking.Core.Params.Data.UnifiedTrackingMutator] Debug: Reading configuration...
[VRCFaceTracking.Core.MainStandalone] Debug: Starting OSC update loop...
[VRCFaceTracking.Services.ActivationService] Debug: Checking for deletion requests for installed modules...
[VRCFaceTracking.Services.ActivationService] Information: Checking for updates for installed modules...
[VRCFaceTracking.Core.Params.Data.UnifiedTrackingMutator] Debug: Configuration loaded.
[VRCFaceTracking.Services.ActivationService] Information: Initializing modules...
[VRCFaceTracking.Core.Library.UnifiedLibManager] Information: Starting initialization tracking
[VRCFaceTracking.Core.Library.UnifiedLibManager] Information: Tearing down all modules...
[Microsoft.Extensions.Hosting.Internal.Host] Debug: Hosting starting
[VRCFaceTracking.Core.Library.UnifiedLibManager] Debug: MeowFaceExtTrackingInterface properly implements ExtTrackingModule.
[VRCFaceTracking.Core.Library.UnifiedLibManager] Debug: Initializing requested runtimes...
[VRCFaceTracking.Core.Library.UnifiedLibManager] Information: Initializing runtimes...
[VRCFaceTracking.Core.Library.UnifiedLibManager] Information: Initializing MeowFaceExtTrackingInterface, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[VRCFaceTracking.Core.Library.UnifiedLibManager] Information: Loading External Module MeowFaceExtTrackingInterface, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[Microsoft.Hosting.Lifetime] Information: Application started. Press Ctrl+C to shut down.
[Microsoft.Hosting.Lifetime] Information: Hosting environment: Production
[Microsoft.Hosting.Lifetime] Information: Content root path: C:\Program Files\WindowsApps\96ba052f-0948-44d8-86c4-a0212e4ae047_5.2.3.0_x64__4s4k90pjvq32p\
[Microsoft.Extensions.Hosting.Internal.Host] Debug: Hosting started
[MeowFaceExtTrackingInterface] Information: Seeking MeowFace connection for 60s. Accepting data on 26.167.204.33:12345
[VRCFaceTracking.Core.Library.UnifiedLibManager] Warning: No modules loaded.
[VRCFaceTracking.Core.Services.ModuleDataService] Debug: Failed to get user rating for module 4f56fb2c-009f-4099-bf64-713adb6e0aae

**Comment by hoshimi-kiyoshi** [comment]
you need to set up the app
 26.167.204.33 is your IP
1:2:3:4:5 is the port

**Comment by MiyuriWise** [comment]
> you need to set up the android app 26.167.204.33 is your IP 12345 is the port
> 
> if it's still not connecting, go to your device manager > internet connections and disable abything that isn't connected
> 
> (you don't need to restart, and if your on a VPN turn that off temporarily, if your Internet stops working, turn whatever you turned off back on)

I fixed, it was because radmin vpn but thank you
